import yaml
import sys
import os
import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

def error_exit(message: str):
    print(f"::error::{message}")
    sys.exit(1)

def set_output(name: str, value: str) -> None:
    path = os.getenv("GITHUB_OUTPUT")

    if not path:
        print(f"[set_output] {name}={value}")
        return

    if "\n" not in value:
        with open(path, "a") as f:
            f.write(f"{name}={value}\n")
        return

    delimiter = f"EOF_{uuid.uuid4().hex}"

    with open(path, "a") as f:
        f.write(f"{name}<<{delimiter}\n")
        f.write(value + "\n")
        f.write(f"{delimiter}\n")

manifest_path = os.getenv('INPUT_MANIFEST', 'manifest.yaml')

try:
    with open(manifest_path, 'r') as file:
        manifest = yaml.safe_load(file)
        print(f"Manifest loaded successfully from '{manifest_path}'.", flush=True)
        print(f"Manifest content: {manifest}", flush=True)
except FileNotFoundError:
    error_exit(f"Manifest file '{manifest_path}' not found.")
except yaml.YAMLError as e:
    error_exit(f"Error parsing YAML file: {e}")
except Exception as e:
    error_exit(f"An unexpected error occurred: {e}")

try:
    project_name = manifest["name"]
    version = manifest["version"]
    releases = manifest["releases"]
    related_changes: list = next(r["changes"] for r in releases if r["version"] == version)
except Exception as e:
    error_exit(f"Error extracting data from manifest: {e}")

release_title = f"{project_name} v{version}"
release_version = version
release_body_builder = []
release_body_builder.append(f"## Changes 🚀")
release_body_builder.extend([f"- {change}" for change in related_changes])
release_body_builder.append("\n---\n")
release_body_builder.append("🤖 Generated by [gha-manifest](https://github.com/albr21/gha-manifest) \\")
release_body_builder.append("📅 " + datetime.now(ZoneInfo("Europe/Paris")).replace(microsecond=0).isoformat() + " \\")
release_body_builder.append("📬 Use issues to report bugs or request features.")

release_body = "\n".join(release_body_builder)

set_output("release-title", release_title)
set_output("release-version", release_version)
set_output("release-body", release_body)
